language: ruby
rvm:
- 2.5.0
sudo: false
cache: bundler
before_install:
- chmod +x _scripts/gemfile.sh
- _scripts/gemfile.sh
- npm i -g npm@6.1.0
install:
- npm install
- bundle install
branches:
  only:
  - publish
notifications:
  email:
    recipients:
    - secure: gK8tke5tvf+kn0QCQz8mBdEKDcxgtOKHSkS55k6GGSyGOSBh0wlWVYP0S3pgmJ9zGu6y6y0gBkwhA12t3SbhMXEPeKUnAdBJrss+MJdHk6Z3mhb9BhO/kyKxhkS+oTYrTBXndINEVa0JKrpwVcE3s9b+PWn7B59jKWrcXiZ4a7BMgfyXM+pKi+sJwRnRGBDsa2kbBz1S7slkb1P7t8xN+/JTM+vArHn0Pb0cXmfeW4/9llqTMMHkuscULDrcnkhgQuHWXi4SX9kk42dj9+ga2tI1vkfSuUg0m3BKc3N+wNkPt9NJoXXEJbkfbrOkKKJ8tbKHooi1bNbcwlI9Axmu5QTWQkwCAEtvbbroXch2zzEIg3gOuaFxbCwRjEUEkHP5jWLgIA4gH70ZRgRLEL31AkoRXXgZMjKvHV/IhonGzAz25jdRPf6uReMGnjwjyDDLTSSacI0yAwSI8No4MDMs3VuXRP9+6pbg01bwOc1DijTbpfu0zKHuOm2jSTErZdhNPDA2m673lbyt4AbqGqXWigWFAPLnB5SBNS63O7IluYu8SwS0rh6oQppsJF6RNB7EQ4VSuvYYJ2a0NZbT7QZ47hJrbkNFfBsa+vBXKYtZZ2gaBqGGkGNA7VGhob2Hd8Y0GKl0gEBRH7UgpxRhpw3IMwE/1Csn8mYxKhlEXm5wi/c=
    - secure: ThPSgqgVNLGilY8sUdKvEQmGuQocuoVuoRYdjaH6pojpsREXlNb5Yv8MlWLWRTY+JvhZcFAmE+B4e5lUT6PCgKoeidM94tzhuRj+wI3c88Y+HHe6P1p+hnQH5aVGNQTchxLF3Bdio412d2KLqhvO1+fWGLIsw12EuoMezGsuCfOCkR3fR2G7dn7IKiJEtwluee4eY59bPI90ucYRTJdZAHYg13JsBWo+D40hpuPYnqJNAk8uM9XQVGoYU4VWclFm1gfok3hzhIgncgxdIyuDy73f6WZ9hnvv73eo0FJUrn9CPAve+fNhOElpqtBCZlSU7Axe8NyDZZDcXAvakLqCPWmlwgu+UuwoVPaYQNyrzSIePT18tocSa4UYBtXu46kryT4g0oD6CQmZ5tcXcqGQi3K+2OmJjYvy9TeCde3YERRVX8JEudTBkNLccJaSpxr6grIP/+LIyBsnAbKFeq2yrXYCnRmA1iyD603vaed8y37uufH3WGAjZgRVN5dAo0P5feJ1EH9GuTH1YXw44yKcymYtBNX+sgm0MBZTZMCw2metm+JB6Jc3ji4qGxd3Fpe2CtcOLasPZzU0ifvUTpiqaA9/LqeHRev2i/cXxaxvXdbpRWpVzkVKfFkSFDjqQqJUZ2Z52ATD0/qJ/k20+dC2X318HPtI60AKyfUs61ydaho=
    - secure: IOJLMgek9M6Irp3WsTyuDTGzia29Vs0zWzqNg6kGS2oqQAwwdiVATND+2OwYt+zXieS6/0qJm5gq8gQbFohlmqDQ6utLuugvKi6B22DT5yQGzkeMCr5wNlrag11jFS1uULPhRApwCz5ThnYY33Oiaac4csCBNZ5YMpb4pIQugSBkyFob2oMMZlegL/2yXOtjhLkYJxQvJ5D2zpl+3oQFgmHo7n6XY0c0lJY2bFs9ehY2aXGiTw1WheLDiMMoraCSXxSrYskPOzp7c6ywg1CsdnZAy3IxJaCWEDCBEGmgh2Ljnlh0lTeWYIgow4L8TWOYYrQeU8IolfHRlx1hgCTKmildsyVrTmtLbuKVaUYzvYnuZmlHWF4d+OEkW1RCTmx3gb7iQUEZu28QsCHOgFRZPpI8Um+1ApXM3JcJI4r7zF+qduyLkRR6mdYHTDplhs/nttZYlsWGOkQnqIiJWmPQUeYgSuQgz+3sSnVmA8kNEcPlolH7U+299aL7yAw9z/khNLhErsAYqUI/35E3kecIZeLVFfCKFF1pTQedNCxhxu3lgHNROLu0Q7nXxgrpC2OGBoaR9dwvkdS9MW2Lnh8rK9lGeMvcRjhJsXfkhyJaPgJWa99O9vNUbLK9FHU/qlrM1cvhxd+Ch8QRat3PF3wv+sPZFEYjhb32pVCXukl7I0w=
    on_success: always
    on_failure: always
before_script:
- npm install -g gulp-cli
script:
- chmod +x _scripts/build.sh
- _scripts/build.sh
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh
after_failure:
- chmod +x _scripts/gemfile.sh
- _scripts/gemfile.sh
- npm i -g npm@6.1.0
- npm install
- bundle install
- chmod +x _scripts/build.sh
- _scripts/build.sh
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh
env:
  global:
  - secure: UXS4WAMKaUFb/WIv0bam2q7T36hNXKTgUVeWSSISyxkU+Rvd5rDpkLNNC21N7NqNBF1DHUPhBMpwoYKjvTVbUfgsF7bBPLOTPAvz9Fyl7kJjkVTzk+usqFOxm5vYiJrogBro1BH7ZJKMmEqrzYIJtw+2KIvE826E6kxMAVyOHMeRiPXHH8fz2mNoE6D9hYgAL2pOOPFZ6VKQOHWqWSimXGEPH0M2vMp8MO5NFlu3rLJs/30LdeUM7evOOzl1iftLYqNgt9H56jlY0ztjYWOsSr6tIYfpWyKcSgSA5ZnAnP3MVDS3/ym5xOfSe7vNfDuGfbBKYBx9NKlwL6MVAFMsqJyBIz14wjvBT1cl6YHh8o+2su3gUvsn6uDIDk7m2T3WPXylN9/+jNvvzN2Cvi2QeSi/m/jZKBfrH6bL+4KAklpgRl69oek891Zfwln1Yu87bWXsHuT7nXcw+gGHg4xifbQu95RRlMYyhTnMZKC0UwTBwUK7uLsH3/GnwLh9Mzi8Hg4NLMMZIZ5kn2eIeb691Y84she/ZwNuvuHM6ThFWm+L9vT7CBkZP5oKJRRVOvgunv0uh1UpybSsdcyLnyx1mbEW/8X0q3zTvSa2euUsFHkBlfNefr4Q26b+93pS5di6ufpGRBuVrBQKHZdsjJD6FVPZg2oOI1vCgyZsWZO0DM4=
  - secure: J5PE3reG8l3IOyFKxqmRpVdiGwa5Uc8uo5ksJptBDB/8Bju/Y+mlbZy6ELIE+nQcFMo0WqBx59qY5h8PPG2NeLBlpkgPWiKecxiOBIHR4WwPV2EFcBvcFwM++k4YcQpB/bghZP5OzzNO1psOnoNM/V3DNgsy1V8BmsnmqpkF1Y3aQZfsIKwpITFaUFhX/9k29l5dQqS4cWJKktUjei3HNhYB6zst2K5cWxqagTbB2PjPWTIw1uQzQR4PR1XZ0gPq5R8KpI2Rey4HAucDnesgBxSSgoo3DppHGId8NdXGVh4CxIHowv6PGZtZ5sF/Q7WZcwbSMDstf+ZZ3A4jcJyReadZUsRnE+H+YPrXIS8GwJZ6c0E9s8hN+1lkEog0gzT0sskD4Psv4Yk2NuP+zrNsfxwf9hrNWlOIM2eTF+5LFr5TlwHHKvkByGxfpkePTQBYc1g02EDxzSQnx/nEqL+c0e2lMskT0adTU/lbUkqtsTD4taxAEyZbAseJ0dkIwl4oPSaLwwpMlMcSy7H4SiJzWpI+sU+XNCyg25oDKn3KjcQIzZC5jce1EtgnKY/Ww1FTPI4tPM2r0mq7TnYOI44cH91TiHlMOg/jOBRSmtlhMHcr6Scsy4LegOfAVlj67x+mEvT/GOzbheLS+QtqmU2XFELWS9KHA+N/C6XGkrqXCzE=
  - secure: "TN7hfesCWRGXy57c72lkYYa8aQB20otygIvNtB8KJSq0NrEMA/EpqbnYoP2ancsqmhEBUnWi3bdyyWbBzeK3o9fByotMh3eV3XB/D26jA0i9n27fuZg8a8gHAsSxDyhCri90DEYxxL7fE+5j3nL0+wJzsn4ZO+3eCmvl7Rz6g0+MlnsLUjcBHfxKtqci4r13Q/oNx8f2WHaJlEopucoYU1+cQIuyr1zLXd10IKKb6pwdoWoroPmc1OFI+k7sO0/uj2Z12VVg5nbhMClfSC7tNFnQQp4NaL0mU/zjk91v9L0O0t9BtZqt5Twl8dnKAVA+rwp7wuZpa3CvNdvPCKYziwyFlUnmNKnzNu6KrnkixVz+8ZNESm2L419iTzEAUyp63DfSd+J2DsjIb8OlWp2qdPhUJ7SzKO41/GYtz6sqa/eRz9R/fXCC+MiBp/DPdDV9GFzKgAjGWTRvDztNyk+1Z5/Xl29Y1F229VUc9yaF5IaUwZJkRL9ysDZQA7W9/qrABOfXHgdln/Td9u75K87nlKrSgNRWD11bzQ7pQtDmZJ2HluA+k1uIXbgSHCUk7QpCfyPTKYj45wf7UbRt+DZ/HoSbOGX/8NCKngsTVE5JZgmLCy3cPmFVTOYiRX/pfFIfiFS2QDn4PMwlK/p23ohbxzwdIVCAuYTD5KNibP5YT/s="
