language: ruby
rvm:
- 2.5.0
env:
  global:
    secure: bEA+p8l0Vi5T90DPWIal98ps+NU7acHNoyLBQklA1GZFoRBPZkxChgHDSry4HLDTBBt8vp2hhITWBz9/Ygar+WsJGyUsD+zyiYKMp8RcE14XJOwToXb9SFxD5uAGsNcQ9LhUl2ihvDBU8fIVGG/u3lmSspWRTcA9LAXtlL5ODCRVH7HRXY4JkF1teK4hh8fD5Eq+74FHBZ6W5Z5KffQqaZmb2ULcdR4bf02uEhdrKwlIEDPToBLHTKXwdlnU/u1EYZ/nRAU3UogTJeGS5nAh690ebP7UWRb1dQCnv6u3CLvysi+AjaFADlqPHvXuat54PBVSBSFFMhC0Yl0KQ7Gy43n8cSu2TV5doifielIraDSaID5eVnMeRtPYyGTawhX1z5kqspKJ5m9keLe0pnu8KZqKH4VQwo/YqhXXX0RAGcDjqgg8nO7eO+yyIJmGTWP3MbZM8RoihJ4Hdv10Ko6K44hOFMJiiRZ8BAOthBopIrqN7k/QHdlIw3tkLjZB4+JTk1d5YDmi/c490T+5YeL4moP0oqwNck9cNK5hqk+AuSwm3ZWuKvu6hC5nrdfynJorv0muiikSvnSC7RU3CR/nev8AeDC5Pf1zQ5PCs5XZtBj7ylu+8vrLlcQpdzgK2taafttsHuNwQVbA4qd2y7T3Sbj33nO/IZYIdwduUmGQOmA=
before_install:
- chmod +x _scripts/gemfile.sh
- _scripts/gemfile.sh
- npm i -g npm@6.1.0
install:
- npm install
- bundle install
- gem install jekyll
- gem install jekyll-feed
- gem install jekyll-sitemap
branches:
  only:
  - publish
notifications:
  email:
    recipients:
    - EMAILVAR
    on_success: always
    on_failure: always
before_script:
- npm install -g gulp-cli
script:
- chmod +x _scripts/build.sh
- _scripts/build.sh
sudo: false
addons:
  apt:
    packages:
    - ncftp
